version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Path to the .env file
    # Add volumes or other settings as needed
    # volumes:
    #   - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # Add environment variables or volumes as needed
    # environment:
    #   API_URL: "http://backend:8000"
